/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.practica.programacion.gui;

import com.practica.programacion.Cliente;
import com.practica.programacion.Producto;
import com.practica.programacion.Producto.EstadoProducto;
import com.practica.programacion.Producto.TipoProducto;
import com.practica.programacion.Tienda;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Santiago Hernández
 */
public class AñadirProductos extends javax.swing.JDialog {

    DateFormat sdfDD_MM_YYYY = new SimpleDateFormat("dd_MM_yyyy");

    /**
     * Creates new form AñadirProductos
     * @param parent
     * @param modal
     */
    public AñadirProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date fechaActual = new Date();
        tfFechaPublicacion.setText(sdfDD_MM_YYYY.format(fechaActual));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfFechaPublicacion = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        lFechaPublicacion = new javax.swing.JLabel();
        lCategoria = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        lTitulo = new javax.swing.JLabel();
        lDescripcion = new javax.swing.JLabel();
        lEstado = new javax.swing.JLabel();
        lPrecio = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        tfTitulo = new javax.swing.JTextField();
        bRegistrarProducto = new javax.swing.JButton();
        cbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfFechaPublicacion.setEnabled(false);
        tfFechaPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFechaPublicacionActionPerformed(evt);
            }
        });

        lFechaPublicacion.setText("Fecha de publicación:");

        lCategoria.setText("Categoria:");

        lTitulo.setText("Título:");

        lDescripcion.setText("Descripción:");

        lEstado.setText("Estado:");

        lPrecio.setText("Precio:");

        cbCategoria.setModel(new DefaultComboBoxModel<>(TipoProducto.values()));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        bRegistrarProducto.setText("Registrar producto");
        bRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarProductoActionPerformed(evt);
            }
        });

        cbEstado.setModel(new DefaultComboBoxModel<>(EstadoProducto.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lTitulo)
                    .addComponent(lFechaPublicacion)
                    .addComponent(lPrecio)
                    .addComponent(lEstado)
                    .addComponent(lCategoria)
                    .addComponent(lDescripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bRegistrarProducto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTitulo)
                            .addComponent(tfPrecio)
                            .addComponent(tfFechaPublicacion)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDescripcion))
                        .addGap(38, 38, 38)))
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitulo)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescripcion)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCategoria)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrecio)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFechaPublicacion)
                    .addComponent(tfFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bRegistrarProducto)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarProductoActionPerformed
        Producto producto = new Producto();
        Cliente cliente = (Cliente) Tienda.tienda.getUsuarioLogueado();
        producto.setTitulo(tfTitulo.getText());
        producto.setDescripcion(tfDescripcion.getText());
        producto.setCategoria((TipoProducto) cbCategoria.getSelectedItem());
        producto.setEstado((EstadoProducto) cbEstado.getSelectedItem());
        producto.setPrecio(Double.parseDouble(tfPrecio.getText()));
        try {
            producto.setFechaPublicacion(sdfDD_MM_YYYY.parse(tfFechaPublicacion.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(AñadirProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        cliente.añadirProducto(producto);

        this.dispose();

    }//GEN-LAST:event_bRegistrarProductoActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void tfFechaPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFechaPublicacionActionPerformed

    }//GEN-LAST:event_tfFechaPublicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AñadirProductos dialog = new AñadirProductos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegistrarProducto;
    private javax.swing.JComboBox<TipoProducto> cbCategoria;
    private javax.swing.JComboBox<EstadoProducto> cbEstado;
    private javax.swing.JLabel lCategoria;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lFechaPublicacion;
    private javax.swing.JLabel lPrecio;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfFechaPublicacion;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
