/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.practica.programacion.gui;

import com.practica.programacion.Tienda;
import com.practica.programacion.Usuario;

/**
 *
 * @author Santiago Hernández
 */
public class InicioSesion extends javax.swing.JInternalFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        tfError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCorreo = new javax.swing.JLabel();
        lClave = new javax.swing.JLabel();
        bInicioSesion = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        tfCorreo = new javax.swing.JTextField();
        tfClave = new javax.swing.JTextField();
        tfError = new javax.swing.JTextField();

        setTitle("Inicio Sesión");
        setToolTipText("");

        lCorreo.setText("Correo:");

        lClave.setText("Clave:");

        bInicioSesion.setText("Iniciar Sesión");
        bInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioSesionActionPerformed(evt);
            }
        });

        bRegistrarse.setText("Registrarse");
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });

        tfCorreo.setText("mariadelgado@gmail.com");
        tfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorreoActionPerformed(evt);
            }
        });

        tfClave.setText("2298");
        tfClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClaveActionPerformed(evt);
            }
        });

        tfError.setEditable(false);
        tfError.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lClave, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(bInicioSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRegistrarse))
                    .addComponent(tfError, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfCorreo)
                    .addComponent(tfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCorreo)
                            .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lClave)
                        .addComponent(tfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(tfError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInicioSesion)
                    .addComponent(bRegistrarse))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClaveActionPerformed
    /**
     * Botón que sirve para verificar que existe el usuario y establecerlo como usuario logueado
     */
    private void bInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioSesionActionPerformed
        // TODO add your handling code here:
        tfError.setText("");
        Usuario usuario = Tienda.tienda.verificarUsuario(tfCorreo.getText(), tfClave.getText());
        if (usuario == null) {
            tfError.setText("El correo o la clave son incorrectos");
        } else {
            Tienda.tienda.setUsuarioLogueado(usuario);
            Tienda.tienda.getVentanaPrincipal().usuarioLogueado();
            this.setVisible(false);
        }
    }//GEN-LAST:event_bInicioSesionActionPerformed
    /**
     * Botón que sirve para que acceda a la pantalla de registro a través del método de ventana principal
     */
    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        Tienda.tienda.getVentanaPrincipal().RegistrarUsuario();
        this.setVisible(false);
    }//GEN-LAST:event_bRegistrarseActionPerformed

    private void tfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorreoActionPerformed

    }//GEN-LAST:event_tfCorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInicioSesion;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JLabel lClave;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JTextField tfClave;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfError;
    // End of variables declaration//GEN-END:variables
}
