/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.practica.programacion.gui;

import java.awt.event.ActionEvent;

/**
 *
 * @author Santiago Hernández
 */
public abstract class ListaElementosSwing extends javax.swing.JInternalFrame {//Esta es la clase de swing básica para productos propios, productos por confirmar y gestión tanto de usuarios como productos

    /**
     * Creates new form ProductosPropios
     *
     * @param modelo
     */
    public ListaElementosSwing(ListaElementos modelo) {
        this.modelo = modelo;
        initComponents();
        init();
        ftfFechaDesde.setVisible(false);
        lFechaInicial.setVisible(false);
    }
//variable de tipo ListaElementos 
    ListaElementos modelo;
    
    abstract public void init();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tElementos = new javax.swing.JTable();
        button2 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        ftfFechaDesde = new javax.swing.JFormattedTextField();
        lFechaInicial = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Listas");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        tElementos.setModel(modelo);
        tElementos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tElementos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tElementos);

        button2.setText("button2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button1.setText("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        ftfFechaDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ftfFechaDesde.setToolTipText("");
        ftfFechaDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfFechaDesdeActionPerformed(evt);
            }
        });

        lFechaInicial.setText("Fecha inicial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lFechaInicial)
                        .addGap(18, 18, 18)
                        .addComponent(ftfFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button2)
                    .addComponent(button1)
                    .addComponent(ftfFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFechaInicial))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        button1(evt);
    }//GEN-LAST:event_button1ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        button2(evt);
    }//GEN-LAST:event_button2ActionPerformed

    private void ftfFechaDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfFechaDesdeActionPerformed

    }//GEN-LAST:event_ftfFechaDesdeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton button1;
    protected javax.swing.JButton button2;
    private javax.swing.JFormattedTextField ftfFechaDesde;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lFechaInicial;
    protected javax.swing.JTable tElementos;
    // End of variables declaration//GEN-END:variables

    abstract protected void button2(ActionEvent evt);
    
    abstract protected void button1(ActionEvent evt);
    
}
