/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.practica.programacion.gui;

import com.practica.programacion.Cliente;
import com.practica.programacion.Producto;
import com.practica.programacion.Tienda;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author Santiago H9ernández
 */
public class ProductosPropios extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductosPropios
     */
    public ProductosPropios() {
        init();
        initComponents();
    }
    ListaProductosPropios modelo;

    public void init() {
        Cliente cliente = (Cliente) Tienda.tienda.getUsuarioLogueado();
        modelo = new ListaProductosPropios(cliente.getMisProductos());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        bEliminarProducto = new javax.swing.JButton();
        bAñadirProducto = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Lista de productos propios");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        tProductos.setModel(modelo);
        tProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tProductos);

        bEliminarProducto.setText("Eliminar producto");
        bEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarProductoActionPerformed(evt);
            }
        });

        bAñadirProducto.setText("Añadir producto");
        bAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEliminarProducto)
                .addGap(31, 31, 31)
                .addComponent(bAñadirProducto)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminarProducto)
                    .addComponent(bAñadirProducto))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirProductoActionPerformed
        AñadirProductos añadirProductos = new AñadirProductos(Tienda.tienda.getVentanaPrincipal(), true);
        añadirProductos.setVisible(true);
    }//GEN-LAST:event_bAñadirProductoActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained

    private void bEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarProductoActionPerformed
        int row = tProductos.getSelectedRow();
        if(row >= 0){
                 modelo.removeRow(row);
            modelo.fireTableStructureChanged();     
        }
    }//GEN-LAST:event_bEliminarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadirProducto;
    private javax.swing.JButton bEliminarProducto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tProductos;
    // End of variables declaration//GEN-END:variables
}
