/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.practica.programacion.gui;

import com.practica.programacion.Cliente;
import com.practica.programacion.ClienteProfesional;
import com.practica.programacion.Tienda;

/**
 *
 * @author Santiago Hernández
 */
public class Registrarse extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        establecerPanel();

    }

    public Registrarse(Cliente cliente) {
        initComponents();
        setCliente(cliente);
        establecerPanel();
        bRegistro.setVisible(false);
        tfCorreo.setEnabled(false);
        tfClave.setEnabled(false);
        tfNombre.setEnabled(false);
        tfDNI.setEnabled(false);
        tfTarjetaCredito.setEnabled(false);
        tfUbicacion.setEnabled(false);
        tfDescripcion.setEnabled(false);
        tfHorarioApertura.setEnabled(false);
        tfTelefono.setEnabled(false);
        tfWeb.setEnabled(false);
        rbCliente.setEnabled(false);
        rbClienteProfesional.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lCorreo = new javax.swing.JLabel();
        lClave = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lDNI = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        tfClave = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfDNI = new javax.swing.JTextField();
        lTarjetaCredito = new javax.swing.JLabel();
        lUbicacion = new javax.swing.JLabel();
        tfTarjetaCredito = new javax.swing.JTextField();
        tfUbicacion = new javax.swing.JTextField();
        lTipoCliente = new javax.swing.JLabel();
        rbCliente = new javax.swing.JRadioButton();
        rbClienteProfesional = new javax.swing.JRadioButton();
        bRegistro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfHorarioApertura = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfWeb = new javax.swing.JTextField();
        lDescripcion = new javax.swing.JLabel();
        lHorarioApertura = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        lWeb = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registro");

        lCorreo.setText("Correo:");

        lClave.setText("Clave:");

        lNombre.setText("Nombre:");

        lDNI.setText("DNI:");

        lTarjetaCredito.setText("Tarjeta de crédito:");

        lUbicacion.setText("Ubicación");

        lTipoCliente.setText("Tipo de cliente:");

        buttonGroup1.add(rbCliente);
        rbCliente.setSelected(true);
        rbCliente.setText("Normal");
        rbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbClienteProfesional);
        rbClienteProfesional.setText("Profesional");
        rbClienteProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClienteProfesionalActionPerformed(evt);
            }
        });

        bRegistro.setText("Registrarse");
        bRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistroActionPerformed(evt);
            }
        });

        lDescripcion.setText("Descripción:");

        lHorarioApertura.setText("Horario de apertura:");

        lTelefono.setText("Teléfono:");

        lWeb.setText("Web:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lWeb)
                    .addComponent(lTelefono)
                    .addComponent(lHorarioApertura)
                    .addComponent(lDescripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfHorarioApertura, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfWeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDescripcion)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHorarioApertura)
                    .addComponent(tfHorarioApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefono)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lWeb)
                    .addComponent(tfWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTipoCliente)
                            .addComponent(lUbicacion)
                            .addComponent(lTarjetaCredito)
                            .addComponent(lDNI)
                            .addComponent(lNombre)
                            .addComponent(lClave)
                            .addComponent(lCorreo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCliente)
                                .addGap(18, 18, 18)
                                .addComponent(rbClienteProfesional))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(tfDNI, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfClave, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfUbicacion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTarjetaCredito, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRegistro))
                        .addGap(16, 16, 16)))
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lTipoCliente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbCliente)
                        .addComponent(rbClienteProfesional)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCorreo)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClave)
                    .addComponent(tfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDNI)
                    .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTarjetaCredito)
                    .addComponent(tfTarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUbicacion)
                    .addComponent(tfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bRegistro)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbClienteProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClienteProfesionalActionPerformed
        establecerPanel();
    }//GEN-LAST:event_rbClienteProfesionalActionPerformed
    /**
     * Método que sirve para guardar los datos del nuevo usuario registrado
     */
    private void bRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistroActionPerformed
        Cliente cliente;
        if (jPanel1.isVisible()) {
            ClienteProfesional clienteProfesional = new ClienteProfesional();
            clienteProfesional.setDescripcion(tfDescripcion.getText());
            clienteProfesional.setHorarioApertura(tfHorarioApertura.getText());
            clienteProfesional.setWeb(tfWeb.getText());
            cliente = clienteProfesional;
        } else {
            cliente = new Cliente();
        }
        getCliente(cliente);
        Tienda.tienda.getClientes().add(cliente);
        Tienda.tienda.getVentanaPrincipal().inicioSesion();
        this.dispose();
    }//GEN-LAST:event_bRegistroActionPerformed
    /**
     * Método que sirve para obtener los datos del nuevo usuario
     */
    private Cliente getCliente(Cliente cliente) {
        cliente.setCorreo(tfCorreo.getText());
        cliente.setClave(tfClave.getText());
        cliente.setDNI(tfDNI.getText());
        cliente.setNombre(tfNombre.getText());
        cliente.setTarjetaDeCredito(tfTarjetaCredito.getText());
        cliente.setUbicacion(tfUbicacion.getText());
        return cliente;
    }

    /**
     * Método que sirve para establecer los datos del nuevo usuario
     */
    private void setCliente(Cliente cliente) {
        tfCorreo.setText(cliente.getCorreo());
        tfClave.setText(cliente.getClave());
        tfNombre.setText(cliente.getNombre());
        tfDNI.setText(cliente.getDNI());
        tfTarjetaCredito.setText(cliente.getTarjetaDeCredito());
        tfUbicacion.setText(cliente.getUbicacion());
        if (cliente instanceof ClienteProfesional) {//si el nuevo usuario es un cliente profesional establece los datos del cliente normal + los datos dentro del jpanel
            rbClienteProfesional.setSelected(true);
            tfDescripcion.setText(((ClienteProfesional) cliente).getDescripcion());
            tfHorarioApertura.setText(((ClienteProfesional) cliente).getHorarioApertura());
            tfTelefono.setText(((ClienteProfesional) cliente).getTelefono());
            tfWeb.setText(((ClienteProfesional) cliente).getWeb());
        } else {
            rbClienteProfesional.setSelected(false);

        }

    }

    /**
     * botón de cliente que hace que no salga el jpanel de los datos de cliente
     * profesional
     */

    private void rbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClienteActionPerformed
        establecerPanel();
    }//GEN-LAST:event_rbClienteActionPerformed
    /**
     * Método que sirve para establecer cuando el panel de datos del cliente
     * profesional tiene que salir o no
     */
    private void establecerPanel() {
        if (rbCliente.isSelected()) {
            jPanel1.setVisible(false);
        } else {
            jPanel1.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegistro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lClave;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lHorarioApertura;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTarjetaCredito;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lTipoCliente;
    private javax.swing.JLabel lUbicacion;
    private javax.swing.JLabel lWeb;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbClienteProfesional;
    private javax.swing.JTextField tfClave;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfHorarioApertura;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTarjetaCredito;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfUbicacion;
    private javax.swing.JTextField tfWeb;
    // End of variables declaration//GEN-END:variables

}
